@url = http://localhost:5001
@productId = 620d2e7c-5a7e-06e2-9814-507d920a45a1
@name = Pizza
@cost = 20.51

###
GET {{url}}/products

###
GET {{url}}/products/{{name}}

###
GET {{url}}/products/{{productId}}

###
POST {{url}}/products
Content-Type: application/json

{
  "productId": "{{productId}}",
  "name": "{{name}}",
  "cost": {{cost}}
}

### 
PUT {{url}}/products/{{productId}}
Content-Type: application/json

{
  "productId": "{{productId}}",
  "name": "{{name}}",
  "cost": {{cost}}
}

###
DELETE {{url}}/products/{{productId}}