@url = http://localhost:5001
@productId = 10000000-0000-0000-0000-000000000000
@name = Pizza
@cost = 20.51

###
GET {{url}}/products

###
GET {{url}}/products/name/{{name}}

###
GET {{url}}/products/{{productId}}

###
POST {{url}}/products
Content-Type: application/json

{
  "productId": "{{productId}}",
  "name": "{{name}}",
  "cost": {{cost}}
}

### 
PUT {{url}}/products/{{productId}}
Content-Type: application/json

{
  "productId": "{{productId}}",
  "name": "{{name}}",
  "cost": {{cost}}
}

###
DELETE {{url}}/products/{{productId}}