@url = http://localhost:5006
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YWRlNTZjZDc2ZDQ0OGE1ODA0YmYzYmEwMzNlMTM2ZCIsInVuaXF1ZV9uYW1lIjoiNWFkZTU2Y2Q3NmQ0NDhhNTgwNGJmM2JhMDMzZTEzNmQiLCJqdGkiOiI2NDU1MDkxZS04ZmIyLTQ3MDEtOTk3ZC02YTM4YzBkODc4NzQiLCJpYXQiOiIxNjU4MzQ4MjM5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW4iLCJuYmYiOjE2NTgzNDgyMzksImV4cCI6MTY1ODM1MTgzOSwiaXNzIjoicGl6emEtaXRhbGlhbm8ifQ.PXPTeCdhxnMkeKrTuGHX5oZKZmVe4-iQHUQKWqPISnQ
@refreshToken = secret
@userId = 9b8e26b8-8536-40b0-9e8a-b396b25c3665

###
GET {{url}}

###
POST {{url}}/sign-up
Content-Type: application/json

{
  "email": "pizza-italiano-user3@mail.com",
  "password": "secretAbcas12"
}

###
POST {{url}}/sign-in
Content-Type: application/json

{
  "email": "pizza-italiano-user3@mail.com",
  "password": "secretAbcas12"
}

###
POST {{url}}/change-password
Content-Type: application/json

{
  "email": "pizza-italiano-user3@mail.com",
  "oldPassword": "secretAbcas12",
  "newPassword": "secretAbcas12",
  "newPasswordConfirm": "secretAbcas12"
}

###
GET {{url}}/me
Authorization: Bearer {{accessToken}}

###
GET {{url}}/users/{{userId}}
Authorization: Bearer {{accessToken}}

###
POST {{url}}/refresh-tokens/use
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}",
}

###
POST {{url}}/refresh-tokens/revoke
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}",
}

###
POST {{url}}/access-tokens/revoke
Content-Type: application/json

{
  "accessToken": "{{accessToken}}"
}

###
GET {{url}}/users
Authorization: Bearer {{accessToken}}

###
PUT {{url}}/users/{{userId}}/change-role
Authorization: Bearer {{accessToken}}

{
  "role": "admin"
}