@url = http://localhost:5002


@orderId = 30000000-0000-0000-0000-000000000000
@orderProductId = 10000000-0000-0000-0000-000000000000
@productId = 10000000-0000-0000-0000-000000000000
@quantity = 1
@email = pizza-italiano-user3@mail.com
@user = "user": { "id": "5ade56cd-76d4-48a5-804b-f3ba033e136d", "isAuthenticated": "true", "role": "admin", claims: {} }

###
GET {{url}}/orders

###
GET {{url}}/orders/{{orderId}}

###
POST {{url}}/orders
Content-Type: application/json
Correlation-Context: { {{user}} }

{
  "orderId": "{{orderId}}"
}

###
POST {{url}}/orders/order-product
Content-Type: application/json

{
  "orderId": "{{orderId}}",
  "orderProductId": "{{orderProductId}}",
  "productId": "{{productId}}",
  "quantity": {{quantity}}
}

### 
PUT {{url}}/orders
Content-Type: application/json

{
  "orderId": "{{orderId}}"
}

###
DELETE {{url}}/orders/{{orderId}}/order-product/{{orderProductId}}/quantity/{{quantity}}

###
GET {{url}}/orders/my
Correlation-Context: { {{user}} }